### ISSUE TITLE
Failed to Compile due to minor error in CSS

### ISSUE THREAD

**Issue by harshil1712** [ncw/rcloneguiexperiment#1]
![Screenshot_2019-03-29 React App](https://user-images.githubusercontent.com/18901032/55243064-7be01100-5264-11e9-8013-f933f2eb1a51.png)
On running `npm start` this error was generated. The comments in CSS are different and hence the error. I will send a PR with the fix.

**Comment by ncw** [comment]
THis is fixed now - thanks for the PR
